name: Deploy Bookshelf PHP App

on:
  push: 
    branches: [main]

jobs: 
  deploy:
      runs_on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Iniciando PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.6' 

      - name: Instalando dependencias
        run: composer install 

      - name: Subir para VPS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/bookshelf
            git pull origin main
            composer install 
